version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "list-ec2-instances"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kjzyv7wb5vpj"
s3_prefix = "list-ec2-instances"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
